// LDBlog/src/pages/ArticleDetail/ArticleDetail.tsx
/* eslint-disable react/no-danger-with-children */
import React, { useEffect, useState, useRef,useMemo} from 'react'
import "./index.scss"
import request from "../../utils/request"
import Footer from "../../components/Footer/Footer"
import { withRouter } from 'react-router'
const env = process.env.NODE_ENV;
let iframeUrl = ""
if(env === "development"){
    iframeUrl = "/comment.html"
}else if(env === "production"){
    iframeUrl = "/static/comment.html"
}
function ArticleDetail(props: any) {
    const [articleData, setData] = useState<any>({})
    const [latestFive,setList] = useState([])
    const [articleId, setArticleId] = useState(()=>{
        const { match:{params},location={}} = props
        console.log('props :>> ', props);
        const articleId =  params.articleId || ""
        return articleId
    })
    const comRef = useRef<any>()
    const initData = async () => {
        const resp = await request({
            url: "/article/getArticleById",
            params: { articleId },
            method: "get"
        })
        if (resp && resp.success) {
            const data = resp.data && resp.data[0]
            setData(data || {})
        }
    }
    const getLatestFive = async ()=>{
        const resp = await request({
            url: "/article/getLatestFive",
            method: "get"
        })
        if(resp && resp.success){
            setList(resp.data)
        }
    }
    const handleToDetail = (item:any)=>{
        props.history.push({
            pathname:`/articleDetail/${item.articleCate}/${item._id}`,
            state:{
                articleId: item._id,
                articleCate: item.articleCate
            }
        })
        setArticleId(item._id)
        sessionStorage.setItem("Blog_Nav",item.articleCate)
        sessionStorage.setItem("ArticleId",item._id)
    }   
    useEffect(() => {
        initData()
        document.documentElement.scrollTop = document.body.scrollTop = 0
        comRef.current.onload = function(){
            comRef.current.height = comRef.current.contentDocument.body && comRef.current.contentDocument.body.scrollHeight + 20
        }
    }, [articleId])
    useEffect(()=>{
        getLatestFive()
    },[])
    return (
        <div className="articleDetail">
            <div className="main">
                <div className="content">
                    <div className="title">
                        <h1>{articleData["articleTitle"]}</h1>
                    </div>
                    <div className="article" dangerouslySetInnerHTML={{ __html: articleData["content"] }}>
                    </div>
                    <div id="SOHUCS" ref={comRef}></div>
                    <iframe
                        ref={comRef}
                        style={{ width: "100%", marginTop: "100px",minHeight:"500px",border: "none" }}
                        src={`${iframeUrl}?articleId=${articleId}`}
                    ></iframe>
                </div>
                <div className="side">
                    <div className="bg-white p10">
                        <div>
                            <h2>近期文章</h2>
                        </div>
                        <div>
                            <ul>
                                {
                                    latestFive.map((item:any)=>{
                                        return <li key={item._id} onClick={()=>{handleToDetail(item)}}>
                                            <img src="/imgs/list.png" alt=""/>
                                            <span>{item.articleTitle}</span>
                                        </li>
                                    })
                                }
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <Footer/>
        </div>
    )
}
export default  withRouter(ArticleDetail)

// LDBlogApp/src/views/ArticleDetail.vue
<script setup lang="ts">
import { getArticleById } from '@src/apis';
import { useRoute } from 'vue-router';
import {onMounted,ref,toRaw,watch} from "vue"
import {IArticleModel} from "@src/utils/types"
// 显式加载资源为一个 URL
let route = useRoute()
const articleModel = ref<IArticleModel>()
console.log(`import.meta.env.DEV`, import.meta.env.DEV)
const commentUrl = ref("/comment.html")
if(!import.meta.env.DEV){
  commentUrl.value = "/static/mobile/comment.html"
}
const commentRef = ref()
const initData =async ()=>{
    const resp = await getArticleById({articleId:route.params.articleId});
    if(resp && resp.success){
      articleModel.value = resp.data?resp.data[0]:{}
    }
}
const initIframe = ()=>{
  commentRef.value.onload = function(){
      commentRef.value.height = commentRef.value.contentDocument.body && commentRef.value.contentDocument.body.scrollHeight + 100
  }
}
watch(()=>route.params.articleId,()=>{
  initIframe()
})
onMounted(()=>{
  initData()
  initIframe()
})
</script>


<template>
  <div class="articleDetail">
      <h2 style="text-align: center;">{{articleModel?.articleTitle}}</h2>
      <div v-html="articleModel?.content">
      </div>
      <iframe ref="commentRef" style="width: 100%;min-height: 300px;" :src="`${commentUrl}?articleId=${route.params.articleId}`" frameborder="0"></iframe>
  </div>
</template>

<style lang="scss" scoped>
.articleDetail{
  padding: 40px;
  img{
    min-width: 50%;
  }
}

</style>
